### ISSUE TITLE
Missing zeta_data (maybe?) causing discrepancy in model spectra

### ISSUE THREAD

**Issue by jfrostburke** [tardis-sn/tardis#1138]
I'm a first-time TARDIS user, and I'm trying to reproduce the results of [Heringer et al. 2017](https://iopscience.iop.org/article/10.3847/1538-4357/aa8309/pdf) to make sure I know how to run models correctly before I move on to modeling a supernova I'm writing a paper on (by varying Ni distributions to see how much that affects the early spectra).

Here's a plot of my attempt, compared to the real spectrum I was modelling:
![05bl](https://user-images.githubusercontent.com/39279101/80163617-8ebe3580-858b-11ea-943b-0e3fcd48588c.png)

As you can see the continuum shape is pretty well replicated, but the line intensities are largely wrong.

Here's the yml file I'm using (values from the paper or the documentation):
```
tardis_config_version: v1.0

supernova:
  luminosity_requested: 8.5 log_lsun
  time_explosion: 11 day

atom_data: kurucz_cd23_chianti_H_He.h5

model:
  structure:
    type: specific
    velocity:
      start: 7500 km/s
      stop: 33000 km/s
      num: 3
    density:
      type: branch85_w7

  abundances:
    type: file
    filename: 05bl.csv
    filetype: custom_composition

plasma:
  initial_t_inner: 9765 K
  ionization: nebular
  excitation: dilute-lte
  radiative_rates_type: dilute-blackbody
  line_interaction_type: downbranch

montecarlo:
  seed: 23111963
  no_of_packets: 2.0e+5
  iterations: 10 
  last_no_of_packets: 5.0e+5
  no_of_virtual_packets: 5

spectrum:
  start: 500 angstrom
  stop: 20000 angstrom
  num: 10000
```

And here's the abundance file (values from the paper):
```
Index C O Na Mg Al Si S Ca Ti Cr Fe
0 0.0000 0.0100 0.0000 0.0000 0.0015 0.7000 0.1100 0.0004 0.0533 0.0367 0.0900
1 0.0300 0.1300 0.0030 0.0300 0.0025 0.6800 0.1000 0.0004 0.0100 0.0070 0.0150
2 0.0600 0.8600 0.0060 0.0400 0.0025 0.0200 0.0100 0.0004 0.0004 0.0003 0.0003
3 0.4184 0.5726 0.0000 0.0030 0.0000 0.0050 0.0010 0.0000 0.0000 0.0000 0.0000
```

I'm generating the spectrum just with
```python
sim = run_tardis('05bl.yml')
spec = sim.runner.spectrum_integrated
```
and then saving `spec`. When I start the `run_tardis` line a number of warnings get printed the screen:
```
(tardis) [jburke@supernova.science.lco.global models]$ python save_spec.py -n 05bl
/home/jburke/.conda/envs/tardis/lib/python3.6/importlib/_bootstrap.py:219: QAWarning: pyne.data is not yet QA compliant.
  return f(*args, **kwds)
[tardis.model.base   ][WARNING]  Abundances have not been normalized to 1. - normalizing (base.py:443)
[tardis.plasma.standard_plasmas][INFO   ]  Reading Atomic Data from kurucz_cd23_chianti_H_He.h5 (standard_plasmas.py:74)
[py.warnings         ][WARNING]  sys:1: PerformanceWarning: indexing past lexsort depth may impact performance.
 (warnings.py:99)
[tardis.io.atom_data.base][INFO   ]  Read Atom Data with UUID=6f7b09e887a311e7a06b246e96350010 and MD5=864f1753714343c41f99cb065710cace. (base.py:184)
[tardis.io.atom_data.base][INFO   ]  Non provided atomic data: synpp_refs, photoionization_data (base.py:187)
[py.warnings         ][WARNING]  /home/jburke/.conda/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3414-py3.6-linux-x86_64.egg/tardis/plasma/properties/atomic.py:195: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  zeta_data['atomic_number'] = zeta_data.index.labels[0] + 1
 (warnings.py:99)
[py.warnings         ][WARNING]  /home/jburke/.conda/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3414-py3.6-linux-x86_64.egg/tardis/plasma/properties/atomic.py:196: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  zeta_data['ion_number'] = zeta_data.index.labels[1] + 1
 (warnings.py:99)
[tardis.plasma.properties.atomic][WARNING]  Zeta_data missing - replaced with 1s. Missing ions: [(11, 12), (12, 13), (13, 14), (14, 15), (16, 17), (20, 21), (22, 23), (24, 25), (26, 27)] (atomic.py:215)
[py.warnings         ][WARNING]  /home/jburke/.conda/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3414-py3.6-linux-x86_64.egg/tardis/plasma/properties/atomic.py:195: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  zeta_data['atomic_number'] = zeta_data.index.labels[0] + 1
 (warnings.py:99)
[py.warnings         ][WARNING]  /home/jburke/.conda/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3414-py3.6-linux-x86_64.egg/tardis/plasma/properties/atomic.py:196: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  zeta_data['ion_number'] = zeta_data.index.labels[1] + 1
 (warnings.py:99)
[tardis.plasma.properties.atomic][WARNING]  Zeta_data missing - replaced with 1s. Missing ions: [(11, 12), (12, 13), (13, 14), (14, 15), (16, 17), (20, 21), (22, 23), (24, 25), (26, 27)] (atomic.py:215)
[tardis.simulation.base][INFO   ]  Starting iteration 1/10 (base.py:268)
Running without OpenMP
```

I suspect my line intensities are all wrong because of the `zeta_data missing` warning, but I'm not sure why that's happening, as I believe I'm using the correct atomic data file (`kurucz_cd23_chianti_H_He.h5`). I also had to cut out some lower-velocity bins or else I run into the `zeta_crash` problem as mentioned in [this issue](https://github.com/tardis-sn/tardis/issues/455).

Apologies for the long issue, hopefully the context is useful. Any help troubleshooting this will be greatly appreciated!
