### ISSUE TITLE
Bug in axis labels in simulation/plasma/lines and simulation/plasma/tau_sobolevs

### ISSUE THREAD

**Issue by nvieira-mcgill** [tardis-sn/tardis#1284]
Hi, 

I am trying to determine the atom involved in every one of the interactions given in `plasma/lines` in the HDF file written by TARDIS. If I am understanding correctly, the atomic number Z involved in each of these transitions should be given in `plasma/lines/axis1_label0`. However, these numbers seem to be offset from their true values. 

For example, in a run using the following abundance pattern:
```
  abundances:
    Ga: 0.1247 # Z=31
    Ge: 0.3853 # Z=32
    As: 0.02069 # Z=33
    Se: 0.2269 # Z=34
    Rb: 0.01946 # Z=37
    Sr: 0.02447 # Z=38
    type: uniform
```
Let's say this outputs the file `run.h5`. If then run the following code:

```
import h5py
import numpy as np

f = h5py.File("run.h5", "r+")
dset = f["simulation"] 
Z = sorted(np.array(dset["plasma/selected_atoms/values"]))
Z_lines = np.array(dset["plasma/lines/axis1_label0"])
Z_lines_uniq = sorted(np.unique(Z_lines))
```

I would expect that `Z` and `Z_lines_uniq` would now be identical. However, instead, printing these two to the terminal reveals that the former is [31, 32, 33, 34, 37, 38] (correct), while the latter is [29, 30, 31, 32, 33, 34] (incorrect). The same occurs if I read in `Z_lines` from `plasma/tau_sobolevs/axis1_label0`.

Is this a bug, or am I misunderstanding the physical meaning of axis1_label0?
