### ISSUE TITLE
Kernel crash when running tardis in PR 1295 with high optical depth

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1298]
#### Code Sample, a copy-pastable example if possible

```python
from tardis import run_tardis
from tardis.io.config_reader import Configuration
import numpy as np
from astropy import units as u
import pandas as pd

config = Configuration.from_yaml('tardis_scatter_numba_test.yml')
del config['config_dirname']

config.montecarlo.no_of_packets = 1e7
config.montecarlo.last_no_of_packets = 1e7
config.plasma.line_interaction_type = 'macroatom'
config.montecarlo.no_of_virtual_packets = 3
#config.model.structure.velocity.start = 50_000 * u.km / u.s
#config.model.structure.velocity.stop = 100_000 * u.km / u.s
config.supernova.time_explosion = 10/25 * u.day
del config.model.abundances['Si']
config.model.abundances['Ca'] = 1.0
config.spectrum.start = 500 * u.angstrom

sim = run_tardis(config)
```

```yml
# Example YAML configuration for TARDIS
tardis_config_version: v1.0

supernova:
  luminosity_requested: 9.44 log_lsun
  time_explosion: 10 day
  #distance: 24.2 Mpc

# standard atomic data base; get it from the tardis-refdata repository
atom_data: kurucz_cd23_chianti_H_He.h5

model:
  structure:
    type: specific
    velocity:
      start: 1.1e4 km/s
      stop: 20000 km/s
      num: 20
    density:
      # showing different configuration options separated by comments
      # simple uniform
      #---------------
      #type: uniform
      #value: 1e-40 g/cm^3
      #---------------
      # branch85_w7 - fit of seven order polynomial to W7 (like Branch 85)
      #---------------
      type: branch85_w7
      # default, no need to change
      #w7_time_0: 19.9999584 s
      # default, no need to change
      #w7_rho_0: 3e29 g/cm^3
      #---------------

  abundances:
    type: uniform
    #H: 1.0
    #O: 0.19
    #Mg: 0.03
    Si: 1.0
    #S: 0.19
    #Ar: 0.04
    #Ca: 0.03

plasma:
  #initial_t_inner: 10000 K
  #initial_t_rad: 10000 K
  disable_electron_scattering: no
  ionization: lte
  excitation: lte
  # radiative_rates_type - currently supported are dilute-blackbody, detailed and blackbody
  radiative_rates_type: dilute-blackbody
  # line_interaction_type - currently supported are scatter, downbranch and macroatom
  line_interaction_type: scatter

montecarlo:
  seed: 23111963
  no_of_packets: 1.0e+7
  iterations: 1
  # Number of threads used in OMP mode; uncomment if you want to control the
  # OMP behaviour via the config; otherwise the maximum available number of
  # threads is used or the number specified in the OMP_NUM_THREADS environment
  # variable
  # --------
  nthreads: 1

  last_no_of_packets: 1.e+7
  no_of_virtual_packets: 0

  convergence_strategy:
    type: damped
    damping_constant: 1.0
    threshold: 0.05
    fraction: 0.8
    hold_iterations: 3
    t_inner:
      damping_constant: 1.0

spectrum:
  start: 500 angstrom
  stop: 20000 angstrom
  num: 10000
```

#### Problem description
When running the above code on the PR 1295 branch https://github.com/tardis-sn/tardis/pull/1295, the Python kernel crashes a short while after reaching this output:

[tardis.simulation.base][INFO   ]  Starting iteration 1/1 (base.py:326)
[py.warnings         ][WARNING]  /home/afullard/.conda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

Tested using a Jupyter notebook. Reproduces.

#### Expected Output
Finished tardis run
