### ISSUE TITLE
Number of shells

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#138]
Given this

``` yaml
        velocity:
            start: 1.1e4 km/s
            stop: 2.0e4 km/s
            num: 20
```

How many shells should be created 19 or 20?
