### ISSUE TITLE
getting caught in "ERROR: Comoving nu less than nu_line!" loop

### ISSUE THREAD

**Issue by nvieira-mcgill** [tardis-sn/tardis#1388]
I am currently working on a project where I am running TARDIS many times within an MCMC. Sometimes, in a given TARDIS run, I get the following error:

```
last_line = 1332539829178871.750000
next_line = 1332526203553207.500000
ERROR: Comoving nu less than nu_line!
comov_nu = -60649257189787528.000000
nu_line = 1332532127704044.000000
(comov_nu - nu_line) / nu_line = -46.514293
r = 141585473126954144.000000
mu = 0.974774
nu = 1756830584363662.000000
doppler_factor = -34.521973
cur_zone_id = 4
```

This continues over and over again and does not stop unless I manually terminate the run. This is a big problem because I sometimes run my code for days at a time, and I store the output of my code in a log file, and if I am not checking the log file every now and then, it can easily blow up to several GB in just a few hours due to this bug. 

My questions are:
1. What exactly is the source of the bug? 
2. Is there an easy way to catch it, since no exception is raised when this occurs? Should an exception be raised when this occurs?

**Comment by andrewfullard** [comment]
You appear to be obtaining a Doppler factor that is a large negative number. Can you provide the model configuration you are running to get this error?

**Comment by nvieira-mcgill** [comment]
I should note that the Doppler factor is not always negative when this error comes up. e.g., here are more lines:

```
last_line = 1332539829178871.750000
next_line = 1332526203553207.500000
ERROR: Comoving nu less than nu_line!
comov_nu = -43582581049778952.000000
nu_line = 1332532127704044.000000
(comov_nu - nu_line) / nu_line = -33.706589
r = 130962927158115168.000000
mu = 0.441991
nu = 3135826675784542.000000
doppler_factor = -13.898275
cur_zone_id = 4
last_line = 1332539829178871.750000
next_line = 1332526203553207.500000
ERROR: Comoving nu less than nu_line!
comov_nu = -60649257189787528.000000
nu_line = 1332532127704044.000000
(comov_nu - nu_line) / nu_line = -46.514293
r = 141585473126954144.000000
mu = 0.974774
nu = 1756830584363662.000000
doppler_factor = -34.521973
cur_zone_id = 4
last_line = 1332539829178871.750000
next_line = 1332526203553207.500000
ERROR: Comoving nu less than nu_line!
comov_nu = -106018588932677408.000000
nu_line = 1332532127704044.000000
(comov_nu - nu_line) / nu_line = -80.561751
r = 240435932568150240.000000
mu = -0.652327
nu = -2562804720229996.500000
doppler_factor = 41.368189
cur_zone_id = 4
```

As for the model config: Since I'm running this within an MC, the parameters (specifically the luminosity, density, inner/outer velocity, and abundance pattern) change. So I've gotten this bug before for different sets of those parameters. Here's the configuration which produced the above:

```
tardis_config_version: v1.0

supernova:
  luminosity_requested: 7.9487 log_lsun
  time_explosion: 1.5 day
  distance: 40 Mpc

atom_data: /home/nvieira/scratch/carsus/atom_data_TARDIS_H-Ra_AUTOSTRUCTURE.h5

model:
  structure:
    type: specific
    velocity:
      start: 5.675e4 km/s # 0.1893c
      stop: 8.241e4 km/s # 0.2749c
      num: 20
    density:
      type : power_law
      time_0: 1.5 day
      rho_0: 1.6773e-15 g/cm^3
      v_0: 5.675e4 km/s
      exponent: -3
  abundances:
    H: 1.943e-12
    He: 1.485e-06
    Li: 6.357e-12
    Be: 1.221e-13
    B: 1.425e-12
    C: 6.398e-10
    N: 5.926e-12
    O: 6.949e-11
    F: 1.763e-10
    Ne: 3.481e-11
    Na: 1.975e-11
    Mg: 1.666e-10
    Al: 2.142e-11
    Si: 8.845e-11
    P: 3.908e-11
    S: 9.775e-11
    Cl: 3.459e-12
    Ar: 5.050e-10
    K: 4.413e-11
    Ca: 1.692e-03
    Sc: 1.776e-07
    Ti: 1.416e-04
    V: 2.733e-03
    Cr: 1.890e-02
    Mn: 6.030e-04
    Fe: 7.664e-03
    Co: 7.107e-05
    Ni: 1.561e-02
    Cu: 4.063e-03
    Zn: 9.597e-03
    Ga: 2.656e-03
    Ge: 1.636e-02
    As: 2.693e-03
    Se: 2.197e-02
    Br: 4.377e-03
    Kr: 1.641e-02
    Rb: 2.679e-03
    Sr: 7.587e-03
    Y: 1.021e-03
    Zr: 3.605e-03
    Nb: 8.570e-06
    Mo: 1.025e-03
    Tc: 1.607e-04
    Ru: 2.150e-03
    Rh: 1.394e-04
    Pd: 3.969e-04
    Ag: 1.419e-04
    Cd: 1.548e-04
    In: 1.036e-05
    Sn: 7.268e-05
    Sb: 1.585e-05
    Te: 5.959e-05
    I: 2.664e-05
    Xe: 5.027e-07
    Cs: 2.879e-09
    Ba: 3.449e-13
    type: uniform

plasma:
  disable_electron_scattering: false
  ionization: lte
  excitation: lte
  radiative_rates_type: dilute-blackbody
  line_interaction_type: macroatom

montecarlo:
  seed: 23111963
  no_of_packets: 5e+4
  iterations: 30
  nthreads: 32 
  last_no_of_packets: 1e+5
  no_of_virtual_packets: 10
  convergence_strategy:
    type: damped
    damping_constant: 1.0
    threshold: 0.05
    fraction: 0.8
    hold_iterations: 3

spectrum:
  start: 3200 angstrom
  stop: 24800 angstrom
  num: 10000
```

The atom data I'm using is a synthetic line list created with the `AUTOSTRUCTURE` code.
