### ISSUE TITLE
Segmentation fault in the Monte Carlo Main Loop from TARDIS(master)

### ISSUE THREAD

**Issue by mklauser** [tardis-sn/tardis#168]
If you run TARDIS with more than 1.e+6 packets, the code runs into a segmentation fault. Can someone try to reproduce this behavior. The used config and a backtrace is attached.

<del>I guess this is a bug in the array handover from python to c (see BT). </del>
Config:
```yaml
#Currently only simple1d is allowed
tardis_config_version: v1.0
supernova:
    luminosity_requested: 9.44 log_lsun
    time_explosion: 13 day
#    distance : 24.2 Mpc


atom_data: "run/atomic_topbase.h5"
#atom_data: "run/kurucz_atom_pure_simple2.h5"


model:
        
    
    structure:
        type: specific


        velocity:
            start : 1.1e4 km/s
            stop : 20000 km/s
            num: 20
        
        
        density:
            #showing different configuration options separated by comments
            #simple uniform:
            #---------------
            type : uniform
            value : 1e-15 g/cm^3
            #---------------

            #branch85_w7 - fit of seven order polynomial to W7 (like Branch 85):
            #---------------
            #type : branch85_w7
            
            # default, no need to change!
            #time_0 : 19.9999584 s
            # default, no need to change!
            #density_coefficient : 3e29 
            #---------------
                
    
    abundances:
        type: uniform
        H: 1

plasma:
    initial_t_inner: 8000 K
    initial_t_rads: 8000 K
    disable_electron_scattering: yes
    ionization: lte
    excitation: lte
    #radiative_rates_type - currently supported are lte, nebular and detailed
    radiative_rates_type: dilute-blackbody
    #line interaction type - currently supported are scatter, downbranch and macroatom
    line_interaction_type: scatter
            

montecarlo:
    seed: 23111963
    no_of_packets : 4.0e+5
    iterations: 1
    
    black_body_sampling:
        start: 1 angstrom
        stop: 1000000 angstrom
        num: 1.e+6
    last_no_of_packets: 4.e+6
    no_of_virtual_packets: 2

    convergence_criteria:
        type: specific
        damping_constant: 1.0
        threshold: 0.05
        fraction: 0.8
        hold: 3
        t_inner:
            damping_constant: 1.0
    

spectrum:
    start : 500 angstrom
    stop : 20000 angstrom
    num: 10000
```

BT:
```gdb
Program received signal SIGSEGV, Segmentation fault.
compute_distance2line (result=<synthetic pointer>, storage=0x7fffffffd540, 
    packet=0x7fffffffb220) at tardis/cmontecarlo.c:123
123	      double last_line = storage->line_list_nu[rpacket_get_next_line_id(packet) - 1];
(gdb) bt
#0  compute_distance2line (result=<synthetic pointer>, storage=0x7fffffffd540, 
    packet=0x7fffffffb220) at tardis/cmontecarlo.c:123
#1  montecarlo_compute_distances (storage=0x7fffffffd540, 
    packet=0x7fffffffb220) at tardis/cmontecarlo.c:438
#2  get_event_handler (distance=<synthetic pointer>, storage=0x7fffffffd540, 
    packet=0x7fffffffb220) at tardis/cmontecarlo.c:447
#3  montecarlo_one_packet_loop (storage=storage@entry=0x7fffffffd540, 
    packet=packet@entry=0x7fffffffb220, virtual_packet=virtual_packet@entry=1)
    at tardis/cmontecarlo.c:490
#4  0x00007fffd86efba4 in montecarlo_one_packet (
    storage=storage@entry=0x7fffffffd540, packet=packet@entry=0x7fffffffbf90, 
    virtual_mode=virtual_mode@entry=-1) at tardis/cmontecarlo.c:265
#5  0x00007fffd86e08b5 in __pyx_pf_6tardis_10montecarlo_montecarlo_radial1d (
    __pyx_v_model=__pyx_v_model@entry=0x418e310, 
    __pyx_v_virtual_packet_flag=<optimized out>, __pyx_self=<optimized out>)
    at tardis/montecarlo.c:3545
#6  0x00007fffd86ec9db in __pyx_pw_6tardis_10montecarlo_1montecarlo_radial1d (
    __pyx_self=<optimized out>, __pyx_args=<optimized out>, 
    __pyx_kwds=0x43ce4d0) at tardis/montecarlo.c:1626
#7  0x0000000000563522 in PyEval_EvalFrameEx ()
#8  0x00000000004afb64 in PyEval_EvalCodeEx ()
#9  0x000000000055f310 in PyEval_EvalFrameEx ()
#10 0x00000000004afb64 in PyEval_EvalCodeEx ()
---Type <return> to continue, or q <return> to quit---
#11 0x000000000055f310 in PyEval_EvalFrameEx ()
#12 0x0000000000566bfb in PyEval_EvalCode ()
#13 0x0000000000469499 in ?? ()
#14 0x0000000000469819 in PyRun_FileExFlags ()
#15 0x0000000000469d52 in PyRun_SimpleFileExFlags ()
#16 0x000000000046b65f in Py_Main ()
#17 0x00007ffff6f17b45 in __libc_start_main (main=0x46b71d <main>, argc=2, 
    argv=0x7fffffffe058, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe048) at libc-start.c:287
#18 0x0000000000573f2e in _start ()
```
