### ISSUE TITLE
Unable to produce SDEC plots

### ISSUE THREAD

**Issue by rayadastidar** [tardis-sn/tardis#1828]
Hi,
I wanted to produce the SDEC Plot for the virtual packets population. For that I set virtual_packet_logging: True in the configuration file under the spectrum property like this:

```
montecarlo:
  seed: 23111963
  no_of_packets: 16.0e+4
  iterations: 20
  nthreads: 1

  last_no_of_packets: 1.e+5
  no_of_virtual_packets: 10

  convergence_strategy:
    type: damped
    damping_constant: 1.0
    threshold: 0.05
    fraction: 0.8
    hold_iterations: 3
    t_inner:
      damping_constant: 0.5

spectrum:
  start: 500 angstrom
  stop:  20000 angstrom
  num: 10000
  virtual:
    virtual_packet_logging: True
```

Then, when I run tardis:
`sim = run_tardis('tardis_example.yml')`

I am getting this error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-89-1a68e481065f> in <module>
      1 #TARDIS now uses the data in the data repo
----> 2 sim = run_tardis('tardis_example.yml')

/mnt/MyStuff/TARDIS/tardis/tardis/base.py in run_tardis(config, atom_data, packet_source, simulation_callbacks, virtual_packet_logging, show_cplots, log_level, specific_log_level, **kwargs)
    107         simulation.add_callback(*cb)
    108 
--> 109     simulation.run()
    110 
    111     return simulation

/mnt/MyStuff/TARDIS/tardis/tardis/simulation/base.py in run(self)
    429         )
    430         self.iterate(
--> 431             self.last_no_of_packets, self.no_of_virtual_packets, last_run=True
    432         )
    433 

/mnt/MyStuff/TARDIS/tardis/tardis/simulation/base.py in iterate(self, no_of_packets, no_of_virtual_packets, last_run)
    366             nthreads=self.nthreads,
    367             last_run=last_run,
--> 368             iteration=self.iterations_executed,
    369         )
    370         output_energy = self.runner.output_energy

/mnt/MyStuff/TARDIS/tardis/tardis/montecarlo/base.py in run(self, model, plasma, no_of_packets, no_of_virtual_packets, nthreads, last_run, iteration)
    302 
    303         configuration_initialize(self, no_of_virtual_packets)
--> 304         montecarlo_radial1d(model, plasma, self)
    305         self._integrator = FormalIntegrator(model, plasma, self)
    306         # montecarlo.montecarlo_radial1d(

/mnt/MyStuff/TARDIS/tardis/tardis/montecarlo/montecarlo_numba/base.py in montecarlo_radial1d(model, plasma, runner)
     87     if montecarlo_configuration.VPACKET_LOGGING and number_of_vpackets > 0:
     88         runner.virt_packet_nus = np.concatenate(
---> 89             np.array(virt_packet_nus)
     90         ).ravel()
     91         runner.virt_packet_energies = np.concatenate(

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate
```

What should I do?
