### ISSUE TITLE
config reader oddness

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#184]
When I try to do an NLTE run using something like:

```
tardis_config_version: v1.0

supernova:
    luminosity_requested: 9.44 log_lsun
    luminosity_wavelength_start: 3000 Angstrom
    luminosity_wavelength_end:   4000 Angstrom
    time_explosion: 13 day

atom_data: kurucz_cd23_chianti_H_He.h5

model:
    structure:
        type: specific

        velocity:
            start : 1.2e4 km/s
            stop : 20000 km/s
            num: 20
                        
        density:
            type : power_law
            time_0: 2 day
            rho_0: 1e-11 g/cm^3
            v_0: 11000 km/s
            exponent: -5

    abundances:
        type: uniform
        He: 0.19
        Mg: 0.03
        Si: 0.52
        S: 0.19
        Ar: 0.04
        Ca: 0.03

plasma:
    ionization: nebular
    excitation: dilute-lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: scatter
    nlte: 
        species: [He 1]


montecarlo:
    seed: 23111963
    no_of_packets : 1.0e+5
    iterations: 10
    last_no_of_packets: 2.0e+5
    no_of_virtual_packets: 5

spectrum:
    start: 500 angstrom
    stop: 20000 angstrom
    num: 10000
```

the config reader tells me (amongst other things):

```
tardis.io.config_reader - WARNING - No "species" given - ignoring other NLTE options given:
{   'classical_nebular': False, 'coronal_approximation': False}
```

...but surely I did give it a species? What has gone wrong? @wkerzendorf @mklauser Is this just a wrong message or is something in the NLTE broken?
