### ISSUE TITLE
Test workflow duplicates test runs

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#2820]
The test workflow is set up as 

```
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
```

which duplicates actions across pushes and PR opens. It would be better set up following our other checks to reduce duplication.
