### ISSUE TITLE
Convergence strategy should have its own class

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#646]
Convergence strategy is now a dict, for example:

``` yaml
convergence_strategy:
    t_inner_update_exponent: float
    damping_constant: float
    lock_t_inner_cycles: int
    t_inner:
      damping_constant: float
    t_rad:
      damping_constant: float
    w:
      damping_constant: float
```

We currently have no other way to deal with the convergence strategy other than passing the dict to the `Simulation` and using the `get_convergence_status` defined there.

We should have a base `class Convergence` with subclasses for each type of convergence strategy (currently two types) holding all the necessary values. Then, each subclass would have a `check_converged(self, t_rad, w, t_inner, estimated_t_rad, estimated_w, estimated_t_inner)` method returning True or False depending on the specific convergence type and values.

Then in the `Simulation.from_config` we would call `Convergence.from_config` and only store the `Convergence` instance inside the simulation.

**Note: This is now [TEP009](https://github.com/tardis-sn/tep/blob/master/TEP009_convergence_strategy.rst). I would strongly suggest to fix #647 before proceeding with this though.**
