### ISSUE TITLE
Configuration version 2

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#687]
This is to collect and discuss all the changes that could be implemented in the configuration file syntax and would require a `tardis_config_version` bump due to backwards incompatibility with the current configuration schemata.

Feel free to edit adding ideas and/or comment on the existing ones.

**Proposed:**
1. _YAML implicit resolver for ranges_ (related to but not the same as #679)
    Instead of the long
    ```yaml
    black_body_sampling:
      start: 1 angstrom
      stop: 1000000 angstrom
      num: 1.e+6
    ```
     in the config file one would write something like `black_body_sampling: 1..1000000:1.e+6 angstrom` which would be interpreted as `start..stop[:num] [unit]` and is much shorter. The only drawback is that you cannot specify e.g. start in meters and stop in angstrom which is probably an edgy case anyway.
